### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by skibberz** [connordennison/phasmoeditor#12] opened 2023-12-27 16:35 UTC
i make a save, put it in the game, boot it up and it says "Successfully reverted to backup". how do i fix this?

**Comment by skibberz** [comment] 2023-12-27 16:36
i also turned off steam backup

**Comment by skibberz** [comment] 2023-12-27 16:37
how do i fix?

**Comment by cnnrde** [comment] 2023-12-27 16:45
Can't reproduce - what's in your `%appdata%\..\LocalLow\Kinetic Games\Phasmophobia\SaveFile.txt` folder (attach a screenshot preferably)

**Comment by skibberz** [comment] 2023-12-30 13:45
![Screenshot 2023-12-30 134454](https://github.com/connordennison/phasmoeditor/assets/107322140/e0603f7b-72a0-4d78-a550-8f692c4234db)

**Comment by cnnrde** [comment] 2024-01-16 16:17
Try removing `Player.txt`, `Player-prev.txt`, `SaveFile.txt`, and `steam_autocloud.vdf` - then launch the game and close it. Open the new `SaveFile.txt` with the editor, make your changes and it may work

**Comment by cnnrde** [comment] 2024-02-16 21:44
Closing due to inactivity

**Closed as not planned by cnnrde** 2024-02-16 21:44 UTC
